fixtures:
  repositories:
    archive:
      repo: "https://github.com/voxpupuli/puppet-archive"
      ref: "v7.0.0"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat"
      ref: "v9.0.0"
    cron:
      repo: "https://github.com/puppetlabs/puppetlabs-cron_core"
      ref: "v1.1.0"
    logrotate:
      repo: "https://github.com/voxpupuli/puppet-logrotate"
      ref: "v6.1.0"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "v9.1.0"
  symlinks:
    duplicity: "#{source_dir}"

